name: Publish

# description: Publish package to loash-industries github npm repo
permissions:
  id-token: write
  contents: write
  actions: read
  checks: write

on:
  push:
    branches:
      - main

jobs:
  validate-code:
    if: github.actor != 'github-actions[bot]'
    uses: loash-industries/public-workflows/.github/workflows/js-validate-code.yml@v0.1.0
    with:
      node_version: 22
      npm_client: yarn
      npm_client_production_flag: --frozen-lockfile

  create-tag:
    uses: loash-industries/public-workflows/.github/workflows/js-create-release-tag.yml@v0.1.0
    needs: [ validate-code ]
    with:
      package_json_path: package.json
      add_v_prefix_to_version: 'false'

  publish:
    uses: loash-industries/public-workflows/.github/workflows/js-publish-npm.yml@v0.1.0
    needs: [ create-tag ]
    with:
      node_version: 22
      environment: prd
      npm_client: yarn
    secrets:
      NPM_TOKEN: ${{ secrets.TRINARYEX_NPM_TOKEN }}
